# Generated by Django 3.1 on 2020-12-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='totalItems',
        ),
    ]
