# Generated by Django 3.1 on 2020-12-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_board_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pinAdress',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
